import tsparser from "@typescript-eslint/parser";
import { defineConfig } from "eslint/config";
import obsidianmd from "eslint-plugin-obsidianmd";

export default defineConfig([
	...obsidianmd.configs.recommended,
	{
		files: ["src/**/*.ts"],
		languageOptions: {
			parser: tsparser,
			parserOptions: { project: "./tsconfig.json" },
			globals: {
				window: "readonly",
				document: "readonly",
				console: "readonly",
				setTimeout: "readonly",
				clearTimeout: "readonly",
				NodeJS: "readonly",
				crypto: "readonly",
			},
		},
		rules: {
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"obsidianmd/ui/sentence-case": ["error", {
				brands: [
					// Project-specific brands
					"ServiceNow",
					"Snobby",
					"OAuth",
					"README",
					"SN",
					// Default brands (must be re-listed since custom brands replace defaults)
					"iOS",
					"iPadOS",
					"macOS",
					"Windows",
					"Android",
					"Linux",
					"Obsidian",
					"Obsidian Sync",
					"Obsidian Publish",
					"Google Drive",
					"Dropbox",
					"OneDrive",
					"iCloud Drive",
					"YouTube",
					"Slack",
					"Discord",
					"Telegram",
					"WhatsApp",
					"Twitter",
					"X",
					"Readwise",
					"Zotero",
					"Excalidraw",
					"Mermaid",
					"Markdown",
					"LaTeX",
					"JavaScript",
					"TypeScript",
					"Node.js",
					"npm",
					"pnpm",
					"Yarn",
					"Git",
					"GitHub",
					"GitLab",
					"Notion",
					"Evernote",
					"Roam Research",
					"Logseq",
					"Anki",
					"Reddit",
					"VS Code",
					"Visual Studio Code",
					"IntelliJ IDEA",
					"WebStorm",
					"PyCharm",
				],
				acronyms: [
					// Project-specific acronyms
					"URI",
					// Default acronyms (must be re-listed since custom acronyms replace defaults)
					"API",
					"HTTP",
					"HTTPS",
					"URL",
					"DNS",
					"TCP",
					"IP",
					"SSH",
					"TLS",
					"SSL",
					"FTP",
					"SFTP",
					"SMTP",
					"JSON",
					"XML",
					"HTML",
					"CSS",
					"PDF",
					"CSV",
					"YAML",
					"SQL",
					"PNG",
					"JPG",
					"JPEG",
					"GIF",
					"SVG",
					"2FA",
					"MFA",
					"JWT",
					"LDAP",
					"SAML",
					"SDK",
					"IDE",
					"CLI",
					"GUI",
					"CRUD",
					"REST",
					"SOAP",
					"CPU",
					"GPU",
					"RAM",
					"SSD",
					"USB",
					"UI",
					"OK",
					"RSS",
					"S3",
					"WebDAV",
					"ID",
					"UUID",
					"GUID",
					"SHA",
					"MD5",
					"ASCII",
					"UTF-8",
					"UTF-16",
					"DOM",
					"CDN",
					"FAQ",
					"AI",
					"ML",
				],
				ignoreRegex: [
					// Placeholder paths and URIs that aren't user-facing prose
					"^/[a-z_{}?=/&]+$",
					"^obsidian://",
					"^/Users/",
					"^e\\.g\\. ",
					// Tag placeholder example
					"^tag\\d",
					// Strings containing technical identifiers like sn_ prefix
					"sn_",
				],
			}],
		},
	},
]);
